@startuml usecase
title Диаграмма прецедентов

left to right direction

actor "Оператор данных" as operator
usecase "Загрузка данных в БД" as bd_update
usecase "Форматирование исходных данных" as formating
usecase "Редактирование настроек форматирования" as formating_settings
usecase "Настройка игнорирования листов" as set_ignore
usecase "Добавить настройки листа" as add_sheed
usecase "Удалить настройки листа" as del_sheed
usecase "Просмотр настроек" as show_all_settings
usecase "Получить файл настроек" as get_settings_file

operator --> bd_update
operator --> get_settings_file

operator --> formating
set_ignore .up.> formating: extends
formating ..> (Указать год файла): include
formating ..> (Указать вид файла): include

operator --> formating_settings
add_sheed .up.> formating_settings: extends
del_sheed .up.> formating_settings: extends
show_all_settings .up.> formating_settings: extends

actor "Аналитик" as analitic
usecase "Просмотр дашбордов" as dashboard
usecase "Выгрузка данных c дашборда" as data_from_dash
usecase "Выбор фильров" as filter_for_dash
usecase "Загрузка данных из ViQube" as viqube

analitic --> dashboard
dashboard ..> viqube: include
data_from_dash .up.> dashboard: extends
filter_for_dash .up.> dashboard: extends
@enduml