@startuml class
title Диаграмма классов

class MainWindow {
    year: int
    formatter: Formatter
    settings_window: SettingsWindow
    +selectFile()
    +openSettings()
    +doFormat()
    +sendDataToDB()
}

class SettingsWindow {
    settingsManager: Settings
}

interface Formatter {
    settings: [Sheet]
    +format(file, settings)
}

class UlskFormatter {
    settings: [Sheet]
    +format(file, settings)
}

class FullFormatter {
    settings: [Sheet]
    +format(file, settings)
}

class Settings {
    +addSheet(string)
    +removeSheet(string)
    +ignoreSheet(string)
    +getSettings()
}

class SheetSettings {
    name: string
    iloc_rows: [int]
    iloc_column: [int]
    drop_column: [int]
    m_id: [string]
}

class BDConnection {
    +connect()
    +executeQuery(query)
}

MainWindow o-- SettingsWindow
MainWindow <-- BDConnection
MainWindow o-left- Formatter
Formatter <|-- UlskFormatter
Formatter <|-- FullFormatter
UlskFormatter o-- SheetSettings
FullFormatter o-- SheetSettings
Formatter o-- SheetSettings
SettingsWindow *-- Settings
@enduml
