@startuml component

component "Приложение обработки данных" {
    [GUI] as gui
    [Соединение с БД] as db_conn
    [Редактирование настроек] as stngs_rdct
    [Форматирование данных] as format
}

component "Серверная часть" {
    database DB{
        [PostgreSQL] as postgre
    }
    [ViQube] as viqube
}

component "Портал Visiology" {
    [Дашборд] as dash
}

db_conn <-- format
postgre --> viqube
ViQubeAPI - viqube
postgre <-left- db_conn
dash --( ViQubeAPI
@enduml