@startuml sequence
autonumber

actor Пользователь
participant "Главное окно" as main_w
participant "Окно настроек" as stngs_w
participant "Соединение с БД" as db_conn
participant "Форматтер" as format
participant "Настройки листа" as sheet_settings
participant "PostgreSQL" as postgre

Пользователь -> main_w : Запускает приложение
Пользователь -> main_w : Выбирает файл и параметры
main_w -> format : Форматирует данные
format -> sheet_settings : Получает настройки форматирования
sheet_settings --> format : Возвращает настройки

format --> main_w : Возвращает отформатированные данные
main_w -> db_conn : Отправляет данные в БД
db_conn -> postgre : Запрос на добавление данных
postgre --> db_conn : Данные сохранены
db_conn --> main_w : Подтверждение загрузки

Пользователь -> stngs_w : Открывает настройки
stngs_w -> sheet_settings : Запрашивает текущие настройки
sheet_settings --> stngs_w : Возвращает настройки
Пользователь -> stngs_w : Изменяет настройки
stngs_w -> sheet_settings : Сохраняет изменения

@enduml
