CREATE TABLE SubFed (
	id BIGSERIAL NOT NULL UNIQUE,
	name VARCHAR(255) NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE "Amount_GS" (
	id BIGSERIAL NOT NULL UNIQUE,
	id_SubFed INTEGER NOT NULL,
	year INTEGER NOT NULL,
	"group" VARCHAR(255) NOT NULL,
	status VARCHAR(255) NOT NULL,
	amount REAL NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE "Amount_MS" (
	id BIGSERIAL NOT NULL UNIQUE,
	id_SubFed INTEGER NOT NULL,
	"group" VARCHAR(255) NOT NULL,
	status VARCHAR(255) NOT NULL,
	amount REAL NOT NULL,
	year INTEGER NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE "Gender_GS" (
	id BIGSERIAL NOT NULL UNIQUE,
	gender VARCHAR(255) NOT NULL,
	id_SubFed INTEGER NOT NULL,
	amount REAL NOT NULL,
	year INTEGER NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE "Gender_MS" (
	id BIGSERIAL NOT NULL UNIQUE,
	gender VARCHAR(255) NOT NULL,
	id_SubFed INTEGER NOT NULL,
	amount REAL NOT NULL,
	year INTEGER NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE "Age_GS" (
	id BIGSERIAL NOT NULL UNIQUE,
	category VARCHAR(255) NOT NULL,
	id_SubFed INTEGER NOT NULL,
	amount REAL NOT NULL,
	year INTEGER NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE "Age_MS" (
	id BIGSERIAL NOT NULL UNIQUE,
	category VARCHAR(255) NOT NULL,
	id_SubFed INTEGER NOT NULL,
	amount REAL NOT NULL,
	year INTEGER NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE "EducationalLevel_GS" (
	id BIGSERIAL NOT NULL UNIQUE,
	id_SubFed INTEGER NOT NULL,
	educ_lvl VARCHAR(255) NOT NULL,
	amount REAL NOT NULL,
	year INTEGER NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE "EducationalLevel_MS" (
	id BIGSERIAL NOT NULL UNIQUE,
	id_SubFed INTEGER NOT NULL,
	educ_lvl VARCHAR(255) NOT NULL,
	amount REAL NOT NULL,
	year INTEGER NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE "Educ_spec_GS" (
	id BIGSERIAL NOT NULL UNIQUE,
	id_SubFed INTEGER NOT NULL,
	speciality VARCHAR(255) NOT NULL,
	amount REAL NOT NULL,
	year INTEGER NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE "Educ_spec_MS" (
	id BIGSERIAL NOT NULL UNIQUE,
	id_SubFed INTEGER NOT NULL,
	speciality VARCHAR(255) NOT NULL,
	amount REAL NOT NULL,
	year INTEGER NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE "AcademicDegree_GS" (
	id BIGSERIAL NOT NULL UNIQUE,
	degree VARCHAR(255) NOT NULL,
	id_SubFed INTEGER NOT NULL,
	amount REAL NOT NULL,
	year INTEGER NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE "AcademicDegree_MS" (
	id BIGSERIAL NOT NULL UNIQUE,
	degree VARCHAR(255) NOT NULL,
	id_SubFed INTEGER NOT NULL,
	amount REAL NOT NULL,
	year INTEGER NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE "Exp_GS" (
	id BIGSERIAL NOT NULL UNIQUE,
	category VARCHAR(255) NOT NULL,
	id_SubFed INTEGER NOT NULL,
	amount REAL NOT NULL,
	year INTEGER NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE "Exp_MS" (
	id BIGSERIAL NOT NULL UNIQUE,
	category VARCHAR(255) NOT NULL,
	id_SubFed INTEGER NOT NULL,
	amount REAL NOT NULL,
	year INTEGER NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE "Changeability_GS" (
	id BIGSERIAL NOT NULL UNIQUE,
	id_SubFed INTEGER NOT NULL,
	category VARCHAR(255) NOT NULL,
	amount REAL NOT NULL,
	year INTEGER NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE "GosOrgAmount" (
	id BIGSERIAL NOT NULL UNIQUE,
	id_SubFed INTEGER NOT NULL,
	category VARCHAR(255) NOT NULL,
	amount REAL NOT NULL,
	year INTEGER NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE "Competitions" (
	id BIGSERIAL NOT NULL UNIQUE,
	id_SubFed INTEGER NOT NULL,
	category VARCHAR(255) NOT NULL,
	amount REAL NOT NULL,
	year INTEGER NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE "CitizenParticipation" (
	id BIGSERIAL NOT NULL UNIQUE,
	id_SubFed INTEGER NOT NULL,
	category VARCHAR(255) NOT NULL,
	amount REAL NOT NULL,
	year INTEGER NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE "Substitution" (
	id BIGSERIAL NOT NULL UNIQUE,
	id_SubFed INTEGER NOT NULL,
	category VARCHAR(255) NOT NULL,
	amount REAL NOT NULL,
	year INTEGER NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE "Mentoring" (
	id BIGSERIAL NOT NULL UNIQUE,
	id_SubFed INTEGER NOT NULL,
	year INTEGER NOT NULL,
	category VARCHAR(255) NOT NULL,
	amount REAL NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE "ReserveComposition" (
	id BIGSERIAL NOT NULL UNIQUE,
	id_SubFed INTEGER NOT NULL,
	category VARCHAR(255) NOT NULL,
	amount REAL NOT NULL,
	year INTEGER NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE "ReserveCause" (
	id BIGSERIAL NOT NULL UNIQUE,
	id_SubFed INTEGER NOT NULL,
	cause VARCHAR(255) NOT NULL,
	amount REAL NOT NULL,
	year INTEGER NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE "Attestation" (
	id BIGSERIAL NOT NULL UNIQUE,
	id_SubFed INTEGER NOT NULL,
	result VARCHAR(255) NOT NULL,
	period VARCHAR(255) NOT NULL,
	amount REAL NOT NULL,
	year INTEGER NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE "Ranks" (
	id BIGSERIAL NOT NULL UNIQUE,
	id_SubFed INTEGER NOT NULL,
	appointmentReason VARCHAR(255) NOT NULL,
	period VARCHAR(255) NOT NULL,
	amount REAL NOT NULL,
	year INTEGER NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE "ProfDev_amount" (
	id BIGSERIAL NOT NULL UNIQUE,
	id_SubFed INTEGER NOT NULL,
	category VARCHAR(255) NOT NULL,
	amount REAL NOT NULL,
	year INTEGER NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE "ProfDev_resources" (
	id BIGSERIAL NOT NULL UNIQUE,
	id_SubFed INTEGER NOT NULL,
	resources VARCHAR(255) NOT NULL,
	res_type VARCHAR(255) NOT NULL,
	value_type VARCHAR(255) NOT NULL,
	amount REAL NOT NULL,
	year INTEGER NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE "DPO_GS" (
	id BIGSERIAL NOT NULL UNIQUE,
	id_SubFed INTEGER NOT NULL,
	DPO VARCHAR(255) NOT NULL,
	value_type VARCHAR(255) NOT NULL,
	value_name VARCHAR(255) NOT NULL,
	amount REAL NOT NULL,
	year INTEGER NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE "DPO_GS_other" (
	id BIGSERIAL NOT NULL UNIQUE,
	id_SubFed INTEGER NOT NULL,
	value_type VARCHAR(255) NOT NULL,
	DPO_type VARCHAR(255) NOT NULL,
	amount REAL NOT NULL,
	year INTEGER NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE "DPO_MS" (
	id BIGSERIAL NOT NULL UNIQUE,
	id_SubFed INTEGER NOT NULL,
	DPO_type VARCHAR(255) NOT NULL,
	amount REAL NOT NULL,
	year INTEGER NOT NULL,
	PRIMARY KEY(id)
);

ALTER TABLE "Amount_GS"
ADD FOREIGN KEY(id_SubFed) REFERENCES SubFed(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Amount_MS"
ADD FOREIGN KEY(id_SubFed) REFERENCES SubFed(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Gender_GS"
ADD FOREIGN KEY(id_SubFed) REFERENCES SubFed(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Gender_MS"
ADD FOREIGN KEY(id_SubFed) REFERENCES SubFed(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Age_GS"
ADD FOREIGN KEY(id_SubFed) REFERENCES SubFed(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Age_MS"
ADD FOREIGN KEY(id_SubFed) REFERENCES SubFed(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "EducationalLevel_GS"
ADD FOREIGN KEY(id_SubFed) REFERENCES SubFed(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "EducationalLevel_MS"
ADD FOREIGN KEY(id_SubFed) REFERENCES SubFed(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Educ_spec_GS"
ADD FOREIGN KEY(id_SubFed) REFERENCES SubFed(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "AcademicDegree_GS"
ADD FOREIGN KEY(id_SubFed) REFERENCES SubFed(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "AcademicDegree_MS"
ADD FOREIGN KEY(id_SubFed) REFERENCES SubFed(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Exp_GS"
ADD FOREIGN KEY(id_SubFed) REFERENCES SubFed(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Exp_MS"
ADD FOREIGN KEY(id_SubFed) REFERENCES SubFed(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Changeability_GS"
ADD FOREIGN KEY(id_SubFed) REFERENCES SubFed(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "GosOrgAmount"
ADD FOREIGN KEY(id_SubFed) REFERENCES SubFed(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Competitions"
ADD FOREIGN KEY(id_SubFed) REFERENCES SubFed(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Substitution"
ADD FOREIGN KEY(id_SubFed) REFERENCES SubFed(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "ReserveComposition"
ADD FOREIGN KEY(id_SubFed) REFERENCES SubFed(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "ReserveCause"
ADD FOREIGN KEY(id_SubFed) REFERENCES SubFed(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Attestation"
ADD FOREIGN KEY(id_SubFed) REFERENCES SubFed(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Ranks"
ADD FOREIGN KEY(id_SubFed) REFERENCES SubFed(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "ProfDev_amount"
ADD FOREIGN KEY(id_SubFed) REFERENCES SubFed(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "CitizenParticipation"
ADD FOREIGN KEY(id_SubFed) REFERENCES SubFed(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Mentoring"
ADD FOREIGN KEY(id_SubFed) REFERENCES SubFed(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "ProfDev_resources"
ADD FOREIGN KEY(id_SubFed) REFERENCES SubFed(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "DPO_GS"
ADD FOREIGN KEY(id_SubFed) REFERENCES SubFed(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "DPO_GS_other"
ADD FOREIGN KEY(id_SubFed) REFERENCES SubFed(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Educ_spec_MS"
ADD FOREIGN KEY(id_SubFed) REFERENCES SubFed(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;